version: "3.9" 
services:
  cryar-api:
    depends_on: 
      - mysql-db
    build: .
    image: cryar-api:latest
    networks: 
      backend:
        ipv4_address: 172.16.238.10
    ports: 
      - "8080:8080"
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    networks: 
      backend:
        ipv4_address: 172.16.238.101
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "mysql-docker:/var/lib/mysql"
# Names our volume
volumes:
  mysql-docker:
# Network config
networks: 
  backend:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
